[package]
name = "rust_lib_fleeting"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
chrono = "0.4.39"
flutter_rust_bridge = "=2.7.0"
lazy_static = "1.5.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
sled = "0.34.7"
